[build]
  command = "npm run build"
  publish = "build"  # This is where React puts built files

# SPA routing - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
