# netlify.toml for freelance.wandamccrae.com

# Basic settings for the site
[build]
  publish = "."  # Publishes from the root directory

# Enable SPA (Single Page App) routing for React/Angular/Vue/etc.
# This serves index.html for all paths so the client-side router can handle them
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: If you have a custom 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Optional: Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
